Apr-17 18:16:03.213 [main] DEBUG nextflow.cli.Launcher - $> nextflow run vzv_assembling.nf -entry vzv_full_run -resume
Apr-17 18:16:03.650 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.1
Apr-17 18:16:03.678 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/export/home/agletdinov/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.3,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.1
Apr-17 18:16:03.706 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-17 18:16:03.707 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-17 18:16:03.711 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-17 18:16:03.726 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-17 18:16:03.751 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /export/home/agletdinov/work/git_projects/nextflow_projects/nextflow.config
Apr-17 18:16:03.753 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /export/home/agletdinov/work/git_projects/nextflow_projects/nextflow.config
Apr-17 18:16:03.785 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-17 18:16:04.483 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Apr-17 18:16:04.501 [main] INFO  nextflow.cli.CmdRun - Launching `vzv_assembling.nf` [stupefied_cori] DSL2 - revision: d548835993
Apr-17 18:16:04.501 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-17 18:16:04.502 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Apr-17 18:16:04.511 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /export/home/agletdinov/.nextflow/secrets/store.json
Apr-17 18:16:04.514 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@333c8791] - activable => nextflow.secret.LocalSecretsProvider@333c8791
Apr-17 18:16:04.567 [main] DEBUG nextflow.Session - Session UUID: a0781ea0-1ef8-46c3-85c6-9486bed80338
Apr-17 18:16:04.567 [main] DEBUG nextflow.Session - Run name: stupefied_cori
Apr-17 18:16:04.568 [main] DEBUG nextflow.Session - Executor pool size: 144
Apr-17 18:16:04.575 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Apr-17 18:16:04.579 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=432; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-17 18:16:04.604 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.10.1 build 5891
  Created: 12-01-2024 22:01 UTC (13-01-2024 01:01 MSD)
  System: Linux 3.10.0-1160.15.2.el7.x86_64
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 20-internal-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 62933@bigmem01.hpc02.cmd.su [172.22.22.12]
  CPUs: 144 - Mem: 1007.6 GB (398.1 GB) - Swap: 32.7 GB (32.4 GB)
Apr-17 18:16:04.685 [main] DEBUG nextflow.Session - Work-dir: /export/home/agletdinov/work/git_projects/nextflow_projects/work [nfs]
Apr-17 18:16:04.711 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-17 18:16:04.722 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-17 18:16:04.746 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-17 18:16:04.756 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 145; maxThreads: 1000
Apr-17 18:16:05.135 [main] DEBUG nextflow.Session - Session start
Apr-17 18:16:05.533 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-17 18:16:05.555 [main] WARN  nextflow.script.ScriptBinding - Access to undefined parameter `maxForks` -- Initialise it to a default value eg. `params.maxForks = some_value`
Apr-17 18:16:05.557 [main] INFO  nextflow.Nextflow - R N A S E Q - N F   P I P E L I N E
===================================
reads          : /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/fastq/*R{1,2}*.fastq.gz
adapters       : /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/adapters/adapters.fasta
primer_a       : /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/primers/aADAPTERX_v2.fasta
primer_g       : /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/primers/gXADAPTER_v2.fasta
key_areas      : /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/key_areas/vzv_amplicons.fasta
script         : /export/home/agletdinov/work/git_projects/nextflow_projects/bin/rename_fasta_id.py
kraken2db      : /export/home/public/agletdinov_shared/kraken2db/minikraken2_v2_8GB_201904_UPDATE
outdir         : results/
maxForks       : null

Apr-17 18:16:06.460 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.460 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.465 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-17 18:16:06.473 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=144; memory=1007.6 GB; capacity=144; pollInterval=100ms; dumpInterval=5m
Apr-17 18:16:06.475 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Apr-17 18:16:06.546 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.546 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.557 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.557 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.561 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.561 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.566 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.566 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.572 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.591 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.596 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.597 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.601 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.602 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.606 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.606 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.611 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.611 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.614 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.615 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.630 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-17 18:16:06.630 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-17 18:16:06.632 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: FASTQC, vzv_full_run:VZV:SAMTOOLS_INDEX, vzv_full_run:VZV:SAMTOOLS_STATS, TRIM_4_NUCL, vzv_full_run:VZV:TRIM_PRIMERS, TRIM_PRIMERS, MULTIQC, vzv_full_run:VZV:BWA_MEM_BAM_SORT, vzv_full_run:VZV:SAMTOOLS_CONSENSUS, vzv_full_run:MULTIQC, vzv_full_run:VZV:RENAME_FASTA_ID, vzv_full_run:VZV:KRAKEN2, TRIM_ADAPT, RENAME_FASTA_ID, KRAKEN2, vzv_full_run:VZV:FASTQC, vzv_full_run:VZV:BWA_INDEX, BWA_MEM_BAM_SORT, vzv_full_run:VZV:TRIM_ADAPT, BWA_INDEX, SAMTOOLS_CONSENSUS, SAMTOOLS_INDEX, SAMTOOLS_STATS, vzv_full_run:VZV:TRIM_4_NUCL
Apr-17 18:16:06.633 [main] DEBUG nextflow.Session - Igniting dataflow network (13)
Apr-17 18:16:06.637 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/fastq/; pattern: *R{1,2}*.fastq.gz; options: [checkIfExists:true]
Apr-17 18:16:06.638 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:FASTQC
Apr-17 18:16:06.639 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:TRIM_ADAPT
Apr-17 18:16:06.639 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:TRIM_4_NUCL
Apr-17 18:16:06.639 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:TRIM_PRIMERS
Apr-17 18:16:06.640 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:KRAKEN2
Apr-17 18:16:06.640 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:BWA_INDEX
Apr-17 18:16:06.640 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:BWA_MEM_BAM_SORT
Apr-17 18:16:06.640 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:SAMTOOLS_INDEX
Apr-17 18:16:06.641 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:SAMTOOLS_CONSENSUS
Apr-17 18:16:06.641 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:SAMTOOLS_STATS
Apr-17 18:16:06.641 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:VZV:RENAME_FASTA_ID
Apr-17 18:16:06.641 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vzv_full_run:MULTIQC
Apr-17 18:16:06.642 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_4d7bba13d86fd83d: /export/home/agletdinov/work/git_projects/nextflow_projects/./vzv_modules.nf
  Script_f07639bed1a18ae1: /export/home/agletdinov/work/git_projects/nextflow_projects/./multiqc.nf
  Script_4ef13acd3d3e81ba: /export/home/agletdinov/work/git_projects/nextflow_projects/././modules.nf
  Script_1ed5f1f7a391f460: /export/home/agletdinov/work/git_projects/nextflow_projects/vzv_assembling.nf
Apr-17 18:16:06.642 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Apr-17 18:16:06.642 [main] DEBUG nextflow.Session - Session await
Apr-17 18:16:06.799 [Actor Thread 44] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::bwa; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-9d43a4c5a922ffe5b869963aea5a7998
Apr-17 18:16:06.799 [Actor Thread 43] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::fastp; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-dca6929da757e10e0c2b13430d9bf94a
Apr-17 18:16:06.799 [Actor Thread 45] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::fastqc; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-2472c99747f9fb1a6eef40cd9db2844a
Apr-17 18:16:07.003 [Actor Thread 36] INFO  nextflow.processor.TaskProcessor - [92/acc2a0] Cached process > vzv_full_run:VZV:FASTQC (FastQC on 144-vzv_S3_L001)
Apr-17 18:16:07.003 [Actor Thread 28] INFO  nextflow.processor.TaskProcessor - [9b/ca1571] Cached process > vzv_full_run:VZV:FASTQC (FastQC on 142-vzv_S1_L001)
Apr-17 18:16:07.003 [Actor Thread 32] INFO  nextflow.processor.TaskProcessor - [ba/a9c55b] Cached process > vzv_full_run:VZV:FASTQC (FastQC on 143-vzv_S2_L001)
Apr-17 18:16:07.003 [Actor Thread 40] INFO  nextflow.processor.TaskProcessor - [e5/6b8c88] Cached process > vzv_full_run:VZV:FASTQC (FastQC on 146-vzv_S4_L001)
Apr-17 18:16:07.003 [Actor Thread 39] INFO  nextflow.processor.TaskProcessor - [57/d33672] Cached process > vzv_full_run:VZV:TRIM_ADAPT (Fastp on 146-vzv_S4_L001)
Apr-17 18:16:07.003 [Actor Thread 27] INFO  nextflow.processor.TaskProcessor - [66/1f679b] Cached process > vzv_full_run:VZV:TRIM_ADAPT (Fastp on 142-vzv_S1_L001)
Apr-17 18:16:07.003 [Actor Thread 21] INFO  nextflow.processor.TaskProcessor - [f4/f8ee57] Cached process > vzv_full_run:VZV:BWA_INDEX (Bwa index for /export/home/agletdinov/work/git_projects/nextflow_projects/test/vzv/key_areas/vzv_amplicons.fasta)
Apr-17 18:16:07.003 [Actor Thread 35] INFO  nextflow.processor.TaskProcessor - [23/33a254] Cached process > vzv_full_run:VZV:TRIM_ADAPT (Fastp on 144-vzv_S3_L001)
Apr-17 18:16:07.003 [Actor Thread 31] INFO  nextflow.processor.TaskProcessor - [22/9bc0bf] Cached process > vzv_full_run:VZV:TRIM_ADAPT (Fastp on 143-vzv_S2_L001)
Apr-17 18:16:07.023 [Actor Thread 60] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::cutadapt; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-8ae3c5bb9bca6e534661f65a256fa68e
Apr-17 18:16:07.033 [Actor Thread 28] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'PublishDir' minSize=10; maxSize=432; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-17 18:16:07.040 [Actor Thread 59] INFO  nextflow.processor.TaskProcessor - [c1/fee44b] Cached process > vzv_full_run:VZV:TRIM_4_NUCL (Cutadapt on 142-vzv_S1_L001)
Apr-17 18:16:07.041 [Actor Thread 55] INFO  nextflow.processor.TaskProcessor - [1f/744558] Cached process > vzv_full_run:VZV:TRIM_4_NUCL (Cutadapt on 146-vzv_S4_L001)
Apr-17 18:16:07.041 [Actor Thread 57] INFO  nextflow.processor.TaskProcessor - [42/08b1f3] Cached process > vzv_full_run:VZV:TRIM_4_NUCL (Cutadapt on 144-vzv_S3_L001)
Apr-17 18:16:07.044 [Actor Thread 53] INFO  nextflow.processor.TaskProcessor - [3f/4f2d56] Cached process > vzv_full_run:VZV:TRIM_4_NUCL (Cutadapt on 143-vzv_S2_L001)
Apr-17 18:16:07.071 [Actor Thread 76] INFO  nextflow.processor.TaskProcessor - [a1/e22d93] Cached process > vzv_full_run:VZV:TRIM_PRIMERS (Cutadapt (primers) on 144-vzv_S3_L001)
Apr-17 18:16:07.072 [Actor Thread 74] INFO  nextflow.processor.TaskProcessor - [ad/262098] Cached process > vzv_full_run:VZV:TRIM_PRIMERS (Cutadapt (primers) on 146-vzv_S4_L001)
Apr-17 18:16:07.074 [Actor Thread 80] INFO  nextflow.processor.TaskProcessor - [bb/c9656a] Cached process > vzv_full_run:VZV:TRIM_PRIMERS (Cutadapt (primers) on 143-vzv_S2_L001)
Apr-17 18:16:07.074 [Actor Thread 70] INFO  nextflow.processor.TaskProcessor - [eb/fc9678] Cached process > vzv_full_run:VZV:TRIM_PRIMERS (Cutadapt (primers) on 142-vzv_S1_L001)
Apr-17 18:16:07.081 [Actor Thread 113] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::bwa bioconda::samtools; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-cebcec85ba646e7781f852c7811ad0c5
Apr-17 18:16:07.087 [Actor Thread 114] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=/export/home/agletdinov/mambaforge/envs/kraken2; path=/export/home/agletdinov/mambaforge/envs/kraken2
Apr-17 18:16:07.090 [Actor Thread 105] INFO  nextflow.processor.TaskProcessor - [69/8dca07] Cached process > vzv_full_run:VZV:BWA_MEM_BAM_SORT (Bwa mem on 142-vzv_S1_L001)
Apr-17 18:16:07.090 [Actor Thread 91] INFO  nextflow.processor.TaskProcessor - [27/6e2f25] Cached process > vzv_full_run:VZV:BWA_MEM_BAM_SORT (Bwa mem on 144-vzv_S3_L001)
Apr-17 18:16:07.090 [Actor Thread 101] INFO  nextflow.processor.TaskProcessor - [56/e8cb40] Cached process > vzv_full_run:VZV:BWA_MEM_BAM_SORT (Bwa mem on 143-vzv_S2_L001)
Apr-17 18:16:07.090 [Actor Thread 96] INFO  nextflow.processor.TaskProcessor - [ab/7b8ba3] Cached process > vzv_full_run:VZV:BWA_MEM_BAM_SORT (Bwa mem on 146-vzv_S4_L001)
Apr-17 18:16:07.097 [Actor Thread 95] INFO  nextflow.processor.TaskProcessor - [aa/72ce94] Cached process > vzv_full_run:VZV:KRAKEN2 (Kraken2 on 146-vzv_S4_L001)
Apr-17 18:16:07.097 [Actor Thread 90] INFO  nextflow.processor.TaskProcessor - [9b/f0caf3] Cached process > vzv_full_run:VZV:KRAKEN2 (Kraken2 on 144-vzv_S3_L001)
Apr-17 18:16:07.097 [Actor Thread 140] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=bioconda::samtools; path=/export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-d886792ff01fc93672c370108071bc30
Apr-17 18:16:07.098 [Actor Thread 107] INFO  nextflow.processor.TaskProcessor - [b7/0f56a8] Cached process > vzv_full_run:VZV:KRAKEN2 (Kraken2 on 142-vzv_S1_L001)
Apr-17 18:16:07.098 [Actor Thread 104] INFO  nextflow.processor.TaskProcessor - [73/c23633] Cached process > vzv_full_run:VZV:KRAKEN2 (Kraken2 on 143-vzv_S2_L001)
Apr-17 18:16:07.104 [Actor Thread 132] INFO  nextflow.processor.TaskProcessor - [2e/981f7a] Cached process > vzv_full_run:VZV:SAMTOOLS_STATS (Samtools consensus on 142-vzv_S1_L001)
Apr-17 18:16:07.104 [Actor Thread 126] INFO  nextflow.processor.TaskProcessor - [a7/a293e4] Cached process > vzv_full_run:VZV:SAMTOOLS_INDEX (Samtools index on 146-vzv_S4_L001)
Apr-17 18:16:07.104 [Actor Thread 125] INFO  nextflow.processor.TaskProcessor - [14/372580] Cached process > vzv_full_run:VZV:SAMTOOLS_STATS (Samtools consensus on 144-vzv_S3_L001)
Apr-17 18:16:07.105 [Actor Thread 133] INFO  nextflow.processor.TaskProcessor - [a2/00436a] Cached process > vzv_full_run:VZV:SAMTOOLS_INDEX (Samtools index on 144-vzv_S3_L001)
Apr-17 18:16:07.105 [Actor Thread 110] INFO  nextflow.processor.TaskProcessor - [94/96e8f3] Cached process > vzv_full_run:VZV:SAMTOOLS_INDEX (Samtools index on 143-vzv_S2_L001)
Apr-17 18:16:07.106 [Actor Thread 137] INFO  nextflow.processor.TaskProcessor - [e1/a932d9] Cached process > vzv_full_run:VZV:SAMTOOLS_STATS (Samtools consensus on 143-vzv_S2_L001)
Apr-17 18:16:07.106 [Actor Thread 120] INFO  nextflow.processor.TaskProcessor - [79/0f7eec] Cached process > vzv_full_run:VZV:SAMTOOLS_STATS (Samtools consensus on 146-vzv_S4_L001)
Apr-17 18:16:07.107 [Actor Thread 142] INFO  nextflow.processor.TaskProcessor - [0f/a3cccd] Cached process > vzv_full_run:VZV:SAMTOOLS_INDEX (Samtools index on 142-vzv_S1_L001)
Apr-17 18:16:07.115 [Actor Thread 144] DEBUG nextflow.conda.CondaCache - mamba found local env for environment=/export/home/agletdinov/mambaforge/envs/multiqc; path=/export/home/agletdinov/mambaforge/envs/multiqc
Apr-17 18:16:07.117 [Actor Thread 138] INFO  nextflow.conda.CondaCache - Creating env using mamba: bioconda::samtools:1.20 [cache /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9]
Apr-17 18:16:07.119 [Actor Thread 126] INFO  nextflow.processor.TaskProcessor - [02/e7b911] Cached process > vzv_full_run:MULTIQC (MultiQC)
Apr-17 18:16:12.444 [Actor Thread 139] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vzv_full_run:VZV:SAMTOOLS_CONSENSUS (3); work-dir=null
  error [java.lang.IllegalStateException]: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

Apr-17 18:16:12.462 [Actor Thread 139] ERROR nextflow.processor.TaskProcessor - Error executing process > 'vzv_full_run:VZV:SAMTOOLS_CONSENSUS (3)'

Caused by:
  Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>


java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

	at nextflow.conda.CondaCache.getCachePathFor(CondaCache.groovy:384)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskRun.getCondaEnv0(TaskRun.groovy:602)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.processor.TaskRun$_getCondaEnv_closure5.doCall(TaskRun.groovy:594)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
	at jdk.proxy1/jdk.proxy1.$Proxy31.apply(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.processor.TaskRun.getCondaEnv(TaskRun.groovy:594)
	at nextflow.processor.TaskRun$getCondaEnv$35.call(Unknown Source)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:2136)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:638)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:52)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

	at nextflow.conda.CondaCache.runCommand(CondaCache.groovy:333)
	at nextflow.conda.CondaCache.createLocalCondaEnv0(CondaCache.groovy:304)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.doCall(CondaCache.groovy:257)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.call(CondaCache.groovy)
	at nextflow.file.FileMutex.lock(FileMutex.groovy:106)
	at nextflow.conda.CondaCache.createLocalCondaEnv(CondaCache.groovy:257)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure3.doCall(CondaCache.groovy:361)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure3.call(CondaCache.groovy)
	at groovyx.gpars.dataflow.LazyDataflowVariable$1.run(LazyDataflowVariable.java:70)
	... 3 common frames omitted
Apr-17 18:16:12.473 [Actor Thread 139] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

Apr-17 18:16:12.491 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Apr-17 18:16:12.498 [Actor Thread 139] DEBUG nextflow.Session - The following nodes are still active:
[process] vzv_full_run:VZV:SAMTOOLS_CONSENSUS
  status=ACTIVE
  port 0: (queue) closed; channel: -
  port 1: (cntrl) -     ; channel: $

[process] vzv_full_run:VZV:RENAME_FASTA_ID
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (value) bound ; channel: script
  port 2: (cntrl) -     ; channel: $

Apr-17 18:16:12.501 [main] DEBUG nextflow.Session - Session await > all processes finished
Apr-17 18:16:12.501 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-17 18:16:12.501 [Actor Thread 131] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vzv_full_run:VZV:SAMTOOLS_CONSENSUS (2); work-dir=null
  error [java.lang.IllegalStateException]: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

Apr-17 18:16:12.502 [Actor Thread 124] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vzv_full_run:VZV:SAMTOOLS_CONSENSUS (1); work-dir=null
  error [java.lang.IllegalStateException]: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

Apr-17 18:16:12.504 [Actor Thread 117] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vzv_full_run:VZV:SAMTOOLS_CONSENSUS; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Apr-17 18:16:12.505 [Actor Thread 116] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vzv_full_run:VZV:SAMTOOLS_CONSENSUS (4); work-dir=null
  error [java.lang.IllegalStateException]: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20
  status : 1
  message:
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
      warnings.warn("zstandard could not be imported. Running without .conda support.")
    /export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
      _warnings.warn("Install zstandard Python bindings for .conda support")
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
            return func(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
            raise e
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
            exit_code = create(args, parser)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
            return install(args, parser, "create")
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 469, in install
            index = load_channels(pool, channels, repos)
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
            index = get_index(
          File "/export/home/agletdinov/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
            is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
        RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/bioconda:/noarch/repodata.json] 2375 bytes
    
    `$ /export/home/agletdinov/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /export/home/agletdinov/work/git_projects/nextflow_projects/work/conda/env-b766dac764c7cd1826a05b0c2ab22dd9 bioconda::samtools:1.20`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/export/home/agletdinov/mambaforge/bin/conda
                 CONDA_PREFIX=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_1=/export/home/agletdinov/mambaforge
               CONDA_PREFIX_2=/export/home/agletdinov/mambaforge/envs/reat
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/export/home/agletdinov/mambaforge/bin/python
                   CONDA_ROOT=/export/home/agletdinov/mambaforge
                  CONDA_SHLVL=3
               CURL_CA_BUNDLE=<not set>
         JAVA_LD_LIBRARY_PATH=/export/home/agletdinov/mambaforge/lib/jvm/lib/server
              LD_LIBRARY_PATH=/opt/BEASTv1.10.4/beagle-lib/lib:/opt/BEASTv1.10.4/beagle-
                              lib/lib:/opt/BEASTv1.10.4/beagle-lib/lib:/usr/lib64/mpich/lib
                   LD_PRELOAD=<not set>
                      MANPATH=/usr/share/man/mpich:/usr/share/man:/usr/local/share/man:/opt/puppetla
                              bs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/java/jdk-
                              17.0.6/bin:/export/home/agletdinov/mambaforge/bin:/export/home/agletdi
                              nov/mambaforge/condabin:/export/home/agletdinov/.cargo/bin:/export/hom
                              e/agletdinov/java/jdk-
                              17.0.6/bin:/usr/lib64/mpich/bin:/usr/local/bin:/usr/bin:/usr/local/sbi
                              n:/usr/sbin:/opt/puppetlabs/bin:/opt/BEASTv1.10.4/bin:/export/home/agl
                              etdinov:/export/home/agletdinov/.local/bin:/export/home/agletdinov/bin
                              :/opt/BEASTv1.10.4/bin:/export/home/agletdinov:/export/home/agletdinov
                              /.local/bin:/export/home/agletdinov/bin:/opt/BEASTv1.10.4/bin:/export/
                              home/agletdinov
              PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
                   PYTHONPATH=0
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /export/home/agletdinov/mambaforge
                shell level : 3
           user config file : /export/home/agletdinov/.condarc
     populated config files : /export/home/agletdinov/mambaforge/.condarc
                              /export/home/agletdinov/.condarc
              conda version : 23.11.0
        conda-build version : not installed
             python version : 3.10.10.final.0
                     solver : libmamba (default)
           virtual packages : __archspec=1=haswell
                              __conda=23.11.0=0
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /export/home/agletdinov/mambaforge  (writable)
          conda av data dir : /export/home/agletdinov/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /export/home/agletdinov/mambaforge/pkgs
                              /export/home/agletdinov/.conda/pkgs
           envs directories : /export/home/agletdinov/mambaforge/envs
                              /export/home/agletdinov/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.11.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
                    UID:GID : 5088:5088
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    If you suspect this error is being caused by a malfunctioning plugin,
    consider using the --no-plugins option to turn off plugins.
    
    Example: conda --no-plugins install <package>
    
    Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
    the command line to run the command without plugins enabled.
    
    Example: CONDA_NO_PLUGINS=true conda install <package>

Apr-17 18:16:12.514 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=34; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=58m 54s;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Apr-17 18:16:12.851 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-17 18:16:12.975 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
